const PROJECT_DRAFT = 0;
const PROJECT_PROGRESS = 1;
const PROJECT_DONE = 2;
const PROJECT_READY = 3;

module.exports = {
  PROJECT_DONE,
  PROJECT_DRAFT,
  PROJECT_PROGRESS,

  projectStatus: {
    PROJECT_DONE,
    PROJECT_DRAFT,
    PROJECT_READY,
    PROJECT_PROGRESS
  }
};
